package com.agentplatform.orchestrator.service;

import com.agentplatform.core.config.OllamaChatModelFactory;
import com.agentplatform.memory.ConversationMessage;
import com.agentplatform.memory.InMemoryConversationStore;
import dev.langchain4j.agent.tool.ToolExecutionRequest;
import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.SystemMessage;
import dev.langchain4j.data.message.ToolExecutionResultMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.response.ChatResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link AgentChatService} — conversation history behaviour,
 * id generation, dynamic model selection, backward-compatible stateless calls
 * and failure classification. The {@link ChatModel} is mocked (no network,
 * no quota); {@link OllamaChatModelFactory} resolves the requested model into
 * that mock so tests stay hermetic.
 */
@ExtendWith(MockitoExtension.class)
class AgentChatServiceTest {

    private ChatModel chatModel;
    private OllamaChatModelFactory modelFactory;
    private InMemoryConversationStore store;
    private AgentChatService service;

    @BeforeEach
    void setUp() {
        chatModel = mock(ChatModel.class);
        modelFactory = mock(OllamaChatModelFactory.class);
        store = new InMemoryConversationStore();
        service = new AgentChatService(modelFactory, store);
        // Every request resolves to the same mock model.
        lenient().when(modelFactory.chatModel(any())).thenReturn(chatModel);
    }

    private void stubReply(String reply) {
        when(chatModel.chat(any(ChatRequest.class)))
                .thenReturn(ChatResponse.builder().aiMessage(AiMessage.from(reply)).build());
    }

    // ─── conversationId handling ──────────────────────────────────────────────

    @Test
    @DisplayName("missing conversationId is generated by the backend")
    void chatWithHistory_missingId_generatesOne() {
        stubReply("Hi there!");

        AgentChatResult result = service.chatWithHistory(null, null, "Hello");

        assertThat(result.conversationId()).isNotBlank();
        assertThat(result.conversationId()).doesNotContain(" ");
        assertThat(result.response()).isEqualTo("Hi there!");
        assertThat(store.exists(result.conversationId())).isTrue();
        assertThat(store.messages(result.conversationId())).hasSize(2);
    }

    @Test
    @DisplayName("blank conversationId is treated as missing and generated")
    void chatWithHistory_blankId_generatesOne() {
        stubReply("Hi");
        AgentChatResult result = service.chatWithHistory("   ", null, "Hello");
        assertThat(result.conversationId()).isNotBlank();
    }

    @Test
    @DisplayName("supplied conversationId is respected and persisted under that id")
    void chatWithHistory_givenId_respected() {
        stubReply("Hi");
        AgentChatResult result = service.chatWithHistory("conv-77", "system: be brief", "Hello");

        assertThat(result.conversationId()).isEqualTo("conv-77");
        assertThat(store.exists("conv-77")).isTrue();
        List<ConversationMessage> stored = store.messages("conv-77");
        assertThat(stored).hasSize(2);
        assertThat(stored.get(0).role()).isEqualTo("user");
        assertThat(stored.get(0).content()).isEqualTo("Hello");
        assertThat(stored.get(1).role()).isEqualTo("ai");
        assertThat(stored.get(1).content()).isEqualTo("Hi");
    }

    // ─── history threading ────────────────────────────────────────────────────

    @Test
    @DisplayName("follow-up turns include the full prior transcript in the model request")
    void chatWithHistory_sameId_threadsHistory() {
        when(chatModel.chat(any(ChatRequest.class)))
                .thenReturn(ChatResponse.builder().aiMessage(AiMessage.from("First reply")).build(),
                        ChatResponse.builder().aiMessage(AiMessage.from("Second reply")).build());

        service.chatWithHistory("conv-9", null, "hello");
        service.chatWithHistory("conv-9", null, "world");

        ArgumentCaptor<ChatRequest> captor = ArgumentCaptor.forClass(ChatRequest.class);
        verify(chatModel, times(2)).chat(captor.capture());
        List<ChatRequest> requests = captor.getAllValues();

        // First call carries only the user turn.
        assertThat(requests.get(0).messages()).hasSize(1);
        assertThat(requests.get(0).messages().get(0)).isInstanceOf(UserMessage.class);

        // Second call carries user("hello") + ai("First reply") + user("world").
        List<ChatMessage> secondMessages = requests.get(1).messages();
        assertThat(secondMessages).hasSize(3);
        assertThat(secondMessages.get(0)).isInstanceOf(UserMessage.class);
        assertThat(((UserMessage) secondMessages.get(0)).singleText()).isEqualTo("hello");
        assertThat(secondMessages.get(1)).isInstanceOf(AiMessage.class);
        assertThat(((AiMessage) secondMessages.get(1)).text()).isEqualTo("First reply");
        assertThat(secondMessages.get(2)).isInstanceOf(UserMessage.class);
        assertThat(((UserMessage) secondMessages.get(2)).singleText()).isEqualTo("world");
    }

    @Test
    @DisplayName("a brand-new id starts a fresh conversation with no leaked history")
    void chatWithHistory_freshId_hasCleanHistory() {
        stubReply("a");
        service.chatWithHistory("conv-1", null, "one");
        service.chatWithHistory("conv-2", null, "two");

        assertThat(store.messages("conv-1")).hasSize(2);
        assertThat(store.messages("conv-2")).hasSize(2);
        assertThat(store.messages("conv-2").get(0).content()).isEqualTo("two");
    }

    @Test
    @DisplayName("system prompt is sent first in the request")
    void chatWithHistory_systemPromptFirst() {
        stubReply("ok");
        service.chatWithHistory("conv-1", "You are terse.", "hi");

        ArgumentCaptor<ChatRequest> captor = ArgumentCaptor.forClass(ChatRequest.class);
        verify(chatModel).chat(captor.capture());
        ChatMessage first = captor.getValue().messages().get(0);
        assertThat(first).isInstanceOf(SystemMessage.class);
        assertThat(((SystemMessage) first).text()).isEqualTo("You are terse.");
    }

    // ─── validation & failure handling ────────────────────────────────────────

    @Test
    @DisplayName("blank user message is rejected")
    void chatWithHistory_blankMessage_rejected() {
        assertThatThrownBy(() -> service.chatWithHistory("conv-1", null, ""))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("must not be blank");
        assertThatThrownBy(() -> service.chatWithHistory("conv-1", null, "  "))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    @DisplayName("model failure surfaces a classified message and does not persist the turn")
    void chatWithHistory_modelFails_classifiedAndNotPersisted() {
        when(chatModel.chat(any(ChatRequest.class))).thenThrow(new RuntimeException(
                "HTTP error (429): { \"error\": { \"code\": 429, \"status\": \"RESOURCE_EXHAUSTED\", "
                        + "\"message\": \"Quota exceeded for metric: "
                        + "generativelanguage.googleapis.com/generate_content_free_tier_requests\" } }"));

        assertThatThrownBy(() -> service.chatWithHistory("conv-1", null, "hello"))
                .isInstanceOf(AgentChatException.class)
                .hasMessageContaining("quota")
                .hasMessageContaining("429")
                .hasMessageNotContaining("GEMINI_API_KEY");

        assertThat(store.exists("conv-1")).isFalse();
    }

    @Test
    @DisplayName("empty model response surfaces an AgentChatException")
    void chatWithHistory_emptyModelResponse_fails() {
        when(chatModel.chat(any(ChatRequest.class)))
                .thenReturn(ChatResponse.builder().aiMessage(AiMessage.from("   ")).build());

        assertThatThrownBy(() -> service.chatWithHistory("conv-1", null, "hello"))
                .isInstanceOf(AgentChatException.class)
                .hasMessageContaining("empty response");
    }

    // ─── backward-compatible stateless entry points ──────────────────────────

    @Test
    @DisplayName("stateless chat(prompt, message) returns text and never writes history")
    void chat_stateless_returnsTextNoHistory() {
        stubReply("custom result");
        String response = service.chat("System prompt", "do something");

        assertThat(response).isEqualTo("custom result");
        assertThat(store.count()).isZero();
        verify(chatModel, times(1)).chat(any(ChatRequest.class));
    }

    @Test
    @DisplayName("stateless chat(message) delegates without a system prompt")
    void chat_statelessSingleArg_works() {
        stubReply("plain result");

        ArgumentCaptor<ChatRequest> captor = ArgumentCaptor.forClass(ChatRequest.class);
        String response = service.chat("hello single");

        assertThat(response).isEqualTo("plain result");
        verify(chatModel).chat(captor.capture());
        assertThat(captor.getValue().messages()).hasSize(1);
    }

    @Test
    @DisplayName("stateless chat failure also classifies")
    void chat_stateless_classifiedFailure() {
        when(chatModel.chat(any(ChatRequest.class))).thenThrow(new RuntimeException(
                "HTTP error (401): { \"error\": { \"code\": 401, \"status\": \"UNAUTHENTICATED\" } }"));

        assertThatThrownBy(() -> service.chat("hi"))
                .isInstanceOf(AgentChatException.class)
                .hasMessageContaining("authentication");
    }

    // ─── dynamic model selection ─────────────────────────────────────────────

    @Test
    @DisplayName("chatWithHistory forwards the requested model to the factory")
    void chatWithHistory_forwardsRequestedModel() {
        when(modelFactory.chatModel("qwen2.5")).thenReturn(chatModel);
        stubReply("code result");

        AgentChatResult result = service.chatWithHistory("conv-1", null, "refactor this", "qwen2.5");

        assertThat(result.response()).isEqualTo("code result");
        verify(modelFactory).chatModel("qwen2.5");
    }

    @Test
    @DisplayName("stateless chat forwards the requested model to the factory")
    void chat_stateless_forwardsRequestedModel() {
        when(modelFactory.chatModel("llama3")).thenReturn(chatModel);
        stubReply("general result");

        String response = service.chat("System prompt", "do something", "llama3");

        assertThat(response).isEqualTo("general result");
        verify(modelFactory).chatModel("llama3");
    }

    @Test
    @DisplayName("null model is passed through and left to the factory default")
    void chat_stateless_nullModel_passesThroughNull() {
        stubReply("default result");

        service.chat("System prompt", "hi", null);

        verify(modelFactory).chatModel(null);
    }

    // ─── agent tools: image shortcut ─────────────────────────────────────────

    @Test
    @DisplayName("an image request resolves through ImageTools without any LLM call")
    void chatWithHistory_drawRequest_returnsImageHtmlWithoutModelCall() {
        AgentChatResult result = service.chatWithHistory("conv-img", null, "Draw a rocket ship");

        assertThat(result.response()).startsWith("<div class=\"tool-image-result\">");
        assertThat(result.response()).contains("<img");
        assertThat(result.response()).contains("rocket ship");
        verify(chatModel, never()).chat(any(ChatRequest.class));

        // The exchange is still persisted so the transcript survives navigation.
        assertThat(store.messages("conv-img")).hasSize(2);
        assertThat(store.messages("conv-img").get(1).content()).contains("<img");
    }

    @Test
    @DisplayName("stateless chat honours image-intent prompts too")
    void chat_stateless_drawRequest_returnsImageHtml() {
        String response = service.chat("Create a photo of a mountain lake");

        assertThat(response).startsWith("<div class=\"tool-image-result\">");
        assertThat(response).contains("<img");
        verify(chatModel, never()).chat(any(ChatRequest.class));
        assertThat(store.count()).isZero();
    }

    @Test
    @DisplayName("non-image text like 'withdraw' still hits the LLM (no false trigger)")
    void chat_stateless_withdrawWord_notTreatedAsImageRequest() {
        stubReply("ok");
        String response = service.chat("Withdraw the old credentials please");

        assertThat(response).isEqualTo("ok");
        verify(chatModel, times(1)).chat(any(ChatRequest.class));
    }

    // ─── agent tools: bounded tool-execution loop ────────────────────────────

    private ToolExecutionRequest whatsAppToolRequest() {
        return ToolExecutionRequest.builder()
                .name("sendWhatsAppMessage")
                .arguments("{\"phone\":\"+15551234567\",\"message\":\"hello\"}")
                .build();
    }

    @Test
    @DisplayName("a model tool call is executed and its result fed back to the model")
    void toolLoop_executesToolAndFeedsResultBack() {
        when(chatModel.chat(any(ChatRequest.class)))
                .thenReturn(ChatResponse.builder()
                                .aiMessage(AiMessage.from(List.of(whatsAppToolRequest())))
                                .build(),
                        ChatResponse.builder().aiMessage(AiMessage.from("All set!")).build());

        AgentChatResult result = service.chatWithHistory("conv-tools", null, "Send everyone hello");

        assertThat(result.response()).isEqualTo("All set!");

        ArgumentCaptor<ChatRequest> captor = ArgumentCaptor.forClass(ChatRequest.class);
        verify(chatModel, times(2)).chat(captor.capture());
        List<ChatRequest> requests = captor.getAllValues();

        // Second round contains the tool request + its execution result.
        List<ChatMessage> secondRound = requests.get(1).messages();
        boolean hasToolRequest = secondRound.stream()
                .anyMatch(m -> m instanceof AiMessage && ((AiMessage) m).hasToolExecutionRequests());
        assertThat(hasToolRequest).isTrue();

        ToolExecutionResultMessage toolResult =
                (ToolExecutionResultMessage) secondRound.get(secondRound.size() - 1);
        assertThat(toolResult.toolName()).isEqualTo("sendWhatsAppMessage");
        assertThat(toolResult.text()).contains("WhatsApp message sent to +15551234567");
    }

    @Test
    @DisplayName("a hallucinated tool name returns an error result instead of failing the turn")
    void toolLoop_unknownTool_returnsErrorAndConverges() {
        ToolExecutionRequest bad = ToolExecutionRequest.builder()
                .name("teleport")
                .arguments("{}")
                .build();
        when(chatModel.chat(any(ChatRequest.class)))
                .thenReturn(ChatResponse.builder().aiMessage(AiMessage.from(List.of(bad))).build(),
                        ChatResponse.builder().aiMessage(AiMessage.from("ok")).build());

        AgentChatResult result = service.chatWithHistory("conv-tools", null, "teleport me");

        assertThat(result.response()).isEqualTo("ok");

        ArgumentCaptor<ChatRequest> captor = ArgumentCaptor.forClass(ChatRequest.class);
        verify(chatModel, times(2)).chat(captor.capture());
        List<ChatMessage> secondRound = captor.getAllValues().get(1).messages();
        ToolExecutionResultMessage toolResult =
                (ToolExecutionResultMessage) secondRound.get(secondRound.size() - 1);
        assertThat(toolResult.text()).contains("unknown tool 'teleport'");
        assertThat(toolResult.text()).contains("Available tools");
    }

    @Test
    @DisplayName("a model that never stops calling tools fails with a clear convergence error")
    void toolLoop_neverConverges_fails() {
        when(chatModel.chat(any(ChatRequest.class))).thenAnswer(invocation ->
                ChatResponse.builder().aiMessage(AiMessage.from(List.of(whatsAppToolRequest()))).build());

        assertThatThrownBy(() -> service.chatWithHistory("conv-tools", null, "loop forever"))
                .isInstanceOf(AgentChatException.class)
                .hasMessageContaining("converge");
        verify(chatModel, times(6)).chat(any(ChatRequest.class));
        // Nothing persisted on failure.
        assertThat(store.exists("conv-tools")).isFalse();
    }
}